
services:
  etcd:
    image: 'bitnami/etcd:latest'
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    ports:
      #      客户端通信接口
      - 2379:2379
      #      集群节点通信端口
      - 2380:2380
  etcdkeeper:
    image: evildecay/etcdkeeper:latest
    container_name: "etcdkeeper"
    #    environment:
    #      HOST: "0.0.0.0"
    ports:
      - 12000:8080
    depends_on:
      - etcd
  minio:
    image: minio/minio:latest
    container_name: "minio"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - /data:/data
      - /config:/root/.minio
    command: server /data --console-address ":9001"
    restart: always

  kafka:
    image: 'bitnami/kafka:3.6.0'
    ports:
      - '9092:9092'
      - '9094:9094'
    environment:
      - KAFKA_CFG_NODE_ID=0
      #      - 允许自动创建 topic，线上不要开启
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:9092,CONTROLLER://:9093,EXTERNAL://0.0.0.0:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER

  postgresql:
    image: postgres
    container_name: postgresql
    environment:
      POSTGRES_PASSWORD: '123456'
    ports:
      - "15432:5432"
    volumes:
      - ./pg:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis
    container_name: myredis
    command: [ "redis-server", "--requirepass", "123456" ]
    ports:
      - "6379:6379"
    restart: always